- name: Alacritty
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml
    # Linux
    # macOS

    - name: Install Alacritty (macOS)
      homebrew_cask:
              name: alacritty
      when: is_mac

    - name: Copy Alacritty config
      copy:
        src: ./alacritty.yml
        dest: ~/.config/alacritty/alacritty.yml

