- name: pandoc
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml

    # Linux

    # macOS

    - name: Install pandoc (macOS)
      homebrew:
        name: pandoc
      when: is_mac
