- name: jq
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml

    # Linux

    # macOS

    - name: Install jq (macOS)
      homebrew:
        name: jq
      when: is_mac
