- name: fzf
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml

    # Linux

    # macOS

    - name: Install fzf (macOS)
      homebrew:
          name: the_silver_searcher
      when: is_mac
