- name: Lastpass
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml

    # Linux

    # macOS

    - name: Install lastpass (macOS)
      homebrew_cask:
        name: lastpass
      when: is_mac
