- name: Tmux
  hosts: 127.0.0.1
  connection: local
  tasks:
    - include_vars: ../os.yml
    # Linux
    # macOS
    - name: Install Tmux (macOS)
      homebrew:
        name: tmux
      when: is_mac
    - name: Copy config
      copy:
        src: tmux.conf
        dest: ~/.tmux.conf
