- name: Skype
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: ../os.yml

    # Linux

    # macOS

    - name: Install skype (macOS)
      homebrew_cask:
        name: skype
      when: is_mac
